### PR TITLE
Redis shim, with append-only sets. 

### PR DESCRIPTION
**Pull request by xyclin**
Depends on func-scheduling (in vsreekanti) and ordered set lattices (in master).

### CODE REVIEW

**Comment by cw75** [comment]
Have you tested this shim?

**Comment by xyclin** [comment]
@cw75 no, the test will just be the retwis code.

**Comment by cw75** [comment]
Let's not merge this into master for now. Let's test this single file on your own branch with the retwis stuff @xyclin .

**Comment by vsreekanti** [comment]
@xyclin @cw75 we should figure out what we want to do with this code. Probably makes sense to put it in a separate applications repo or something?

**Comment by xyclin** [comment]
@vsreekanti sure. The fluent user library should stay in master though yeah?

**Comment by vsreekanti** [comment]
Yes, definitely to the user library. Same comment as on the other PR -- let's figure out what to merge and how we should structure the code.

**Pull request closed without merging**
